Review: Fix: Tank Mirrored Health Bar Bug #8
pouladpld/Tank-Mania pull request #11
Opened 2018-03-08 02:04 UTC by andreghub

Please check if the issue was completely fixed.

2018-03-08 03:12 UTC, poulad requested changes

2018-03-08 03:12 UTC, pouladpld commented on Assets/Scripts/Tank/TankBehavior2.cs
>              }
How about this instead?

```c#
_slider.SetDirection(transform.localScale.x > 0 ? Slider.Direction.RightToLeft : Slider.Direction.LeftToRight, true);
```

2018-03-08 03:13 UTC, poulad commented on Assets/Scripts/Tank/TankBehavior2.cs
>              }
This requires the slider to be exactly at center of tank on x axis.

2018-03-08 23:32 UTC, andreghub commented
Applied changes as suggested.

2018-03-09 00:40 UTC, poulad approved these changes

2018-03-09 00:40 UTC, merged